### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' when flask GET called from non-incognito browser

### ISSUE THREAD

**Issue by kf106** [kf106/multichain-semi-open#1]
KFBcoin client if opened in some logged-in Chrome browsers raises a type error. This does not occur in an incognito browser, suggesting it may be a cookie problem with wtforms

```
Traceback (most recent call last):
  File "/home/mikko/kfbcoin-master/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/home/mikko/kfbcoin-master/venv/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/mikko/kfbcoin-master/client.py", line 18, in <module>
    clientAddress = getAddress(multichainCli)
  File "/home/mikko/kfbcoin-master/modules/blockchain.py", line 14, in getAddress
    obj = json.loads(subprocess.check_output([mc + "listaddresses"], shell=True))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

**Comment by kf106** [comment]
Problem is currently worked around by causing launching the client to open an incognito window.

**Comment by kf106** [comment]
This may shed some light: https://stackoverflow.com/questions/44682018/typeerror-object-of-type-bytes-is-not-json-serializable
